### ISSUE TITLE
[DOCS] Publish Security telemetry samples within product guides

### ISSUE THREAD

**Issue by SourinPaul** [elastic/security-docs#1099]
## Description 

**Background:** 
For easier maintainability, we are migrating telemetry samples from within the product into online documentation. The effort is captured [here](https://github.com/elastic/security-team/issues/1720).

The goal is to append the existing product guide @[Telemetry Guide](https://www.elastic.co/guide/en/kibana/7.x/telemetry-settings-kbn.html) to also include security telemetry data. 

Once the page location (url) is finalized, this will be included as a reference within the product.

## Acceptance Test Criteria

- As a user, I can see the version-specific telemetry documentation  (e.g. 7.14 vs 7.15) for my product.

## Notes
- The content (including an overview, telemetry samples, etc.) will be provided by the security team leads involved.

**Comment by stevewritescode** [comment]
Rough draft for the content is [here](https://docs.google.com/document/d/10SjbucS3IyrN1SkRpQWexKhUx_uGS6cqV0SrKJe_Br4/edit). I expect we'll iterate several times on the exact wording before GA, but hopefully this is enough information to determine where this content should go in the online documentation.

@jmikell821  - we'll need to know the URL (e.g. https://www.elastic.co/guide/en/kibana/7.x/telemetry-settings-kbn.html or similar) before 7.16 feature freeze so that we can add a link to the Kibana UI. Is the above content enough information for you to advise us on where it will go in the docs?

**Comment by jmikell821** [comment]
Hey @stevewritescode I'll start composing a draft so I can give you a URL. Is there a specific place in our security docs you'd like for this to reside? Or did we want this to be a standalone section? 

cc: @SourinPaul

**Comment by SourinPaul** [comment]
@jmikell821 resurfacing this request for the documentation URL. It will be great so we can merge the PR in time for FF. Thanks in advance.

**Comment by jmikell821** [comment]
@SourinPaul yes, working on this now and will comment with the URL before Friday.

**Comment by pjhampton** [comment]
Howdy, everybody.

Just checking in. I checked out https://www.elastic.co/guide/en/security/current/advanced-settings.html#telemetry-settings which I believe to be the main branch for docs. Is everything on track for the 7.16.0 release in 3 weeks' time?

**Comment by pjhampton** [comment]
Hey. Friendly nudge - all good on this one for the release in 2 weeks?

**Comment by stevewritescode** [comment]
New docs are merged in https://github.com/elastic/security-docs/pull/1157, I think this is good to close. @SourinPaul can you confirm and close?

**Comment by jmikell821** [comment]
Merged #1157.
