### ISSUE TITLE
Error in Artemis documentation search query examples

### ISSUE THREAD

**Issue by patrickt333** [elastic/security-docs#11]
## Description 

There should not be a space between the number and the size indicator.  For example, the query in the docs is:
```
Search network data for endpoints sending more than 100 MB
Artemis
Are you sure you want to run:

Search network for greater than 100B on active endpoints?
```
This is interpreted by Artemis as 100 Bytes rather than Megabytes

By removing the space, the query is interpreted properly.

```
Search network data for endpoints sending more than 100MB
Artemis
Are you sure you want to run:

Search network for greater than 100000000B on active endpoints?
```

## Acceptance Test Criteria

Users should be able to copy/paste any Artemis example and get the expected results.

## Notes

It's possible that this is really an artemis issue and it should properly interpret either entry, but it currently does not and can create confusion.

**Comment by jmikell821** [comment]
Hey @patrickt333! This was fixed in 3.17 and will be updated on the customer-facing side once the release goes out. 

![image](https://user-images.githubusercontent.com/57149392/80498755-20d28f00-893a-11ea-85eb-ef589063fdfd.png)

**Comment by patrickt333** [comment]
Thanks, Janeen, I suppose I should have searched the issues first.  In a related note, I've just discovered that "endpoint sending bytes" doesn't work as expected and this has apparently been a known issue for some time.  When you perform the search, it shows results for bytes whether they were sent OR received.  Is that something we can look at fixing?  Or should I open a new issue?

**Comment by jmikell821** [comment]
No problem, @patrickt333. Yes, please open an issue in the https://github.com/elastic/endgame-platform repo. This is where we are tracking SMP issues. I would probably tag Jeff Chu to get his attention. 

On a related note, any SMP documentation corrections should be created in the https://github.com/elastic/endgame-platform-docs repo (this issue should have gone there but it was already fixed so that's okay!) 

This current repo, https://github.com/elastic/security-docs is where we will be tracking documentation issues for our new Elastic Security app.

**Comment by patrickt333** [comment]
Thanks, Janeen.  I doubt we're going to fix this at our current state as it has been known for a long time, apparently.  I just figured it would easier to fix the documentation.  I'll post a new issue in the right place.
