### ISSUE TITLE
security ingest data seems missing integrations without Endpoint Security

### ISSUE THREAD

**Issue by 111andre111** [elastic/security-docs#1241]
In this slack discussion
https://elastic.slack.com/archives/C0D1XEXEZ/p1637573516368100

has been raised that on this documenation for ingesting data into security app
https://www.elastic.co/guide/en/security/current/ingest-data.html

it seems for customers we'd only support Elastic Agent with Endpoint Security.

But there is no mention about Elastic Agent without Endpoint Security.

But for sure there are existing integrations from Elastic Agent that ship data and contribute as well into Elastic Security.

Which ones are these.

Additionally, can we please have a better linking to what Elastic Agent is, to an Integration definition and EPR (Elastic Endpoint Registry)?

Maybe this one here can be a good start:
https://www.elastic.co/guide/en/fleet/current/fleet-overview.html
https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html

@nastasha-solomon @joepeeples @jmikell821 

^^ @james-elastic

**Comment by nastasha-solomon** [comment]
Notes from Slack conversation with @jamesspi and @joepeeples yesterday - 

The current [ingest data docs](https://www.elastic.co/guide/en/security/7.15/ingest-data.html) don't mention that users can also set up Elastic Agent with other integrations to ingest data into their environment. We need to: 
- Insert this information at the start of the topic
- Point users towards our [integration docs](https://docs.elastic.co/en/integrations/) for additional info on integrations
- Explain how to filter the Integrations page to find integrations that work with Security (users can select from the category filter)

**Comment by nastasha-solomon** [comment]
Really appreciate you filing this @111andre111! 

Couple of questions for you: 
- Would you mind elaborating on how you'd like to see Elastic Package Registry docs incorporated into the [ingest data docs](https://www.elastic.co/guide/en/security/current/ingest-data.html)? For example, are you requesting that we direct cloud users towards using the EPR because it allows them to access integrations through Kibana or did you have something else in mind? 
- Similar question for your request to define integrations. Is it sufficient to point users towards [these integration docs](https://docs.elastic.co/en/integrations/) for more info, or were you looking for something deeper and more tailored to how the agent works with security integrations?

**Comment by 111andre111** [comment]
Hi @nastasha-solomon 
As of the second point, I think the ingest data docs are very ok.
As of point 1, the EPR documentation might be that one: https://www.elastic.co/guide/en/fleet/current/fleet-overview.html#package-registry-intro

I linked that particular page already in my initial request.

These links should just make clear, that elastic agent needs the integrations, delivered from the epr.

Hope that makes sense.

**Comment by nastasha-solomon** [comment]
Sounds good, thank you @111andre111!

**Comment by nastasha-solomon** [comment]
Merged #1246.
