### ISSUE TITLE
[DOCS][8.0] Document new behavior for displaying all historical alerts when viewing Rule Details

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#1321]
## Description 

As of https://github.com/elastic/kibana/pull/120053, we're now displaying _all historical alerts_ of a Rule on the Rule Details page rather than just the alerts from the most recent Rule instance:

> As discussed with the team and relevant product folks, we're resolving this issue by updating the alerts query to filter by `ruleId` instead of the Rule SO ID, which will result in a slight workflow change where _all alerts_ for a given `ruleId` will be displayed rather than just the latest instance -- i.e. create pre-package rule, generate alerts, delete/re-create pre-package rule, generate alerts, alerts are displayed from both Rule instances instead of just the most recent. 

I had marked https://github.com/elastic/kibana/pull/120053 as `release_note:skip`, but after seeing this issue opened as a result of the change in behavior (https://github.com/elastic/kibana/issues/120905) it seems like it would be a good idea to have a blurb about this in the `8.0` release notes (and/or update any existing documentation as necessary).

If you feel this is better suited as a line-item in the release notes, I can update the title of https://github.com/elastic/kibana/pull/120053 to something like `Updates Rule Details to show all historical alerts for a given Rule` and change to `release_note:feature`, however may be worth expanding a bit on this change? Let me know, thanks! 🙂

**Comment by joepeeples** [comment]
This change seems release-note-worthy to me, since it could result in an observable change in behavior. @nastasha-solomon and @jmikell821 know the release notes a lot better than I do, though.

I was also checking the current docs to see if we described the old way of displaying alerts on the rule details page, which we don't. @spong, do you think this needs to be in the docs, to explain how the list of alerts is populated? If I understand the change, it seems like the list has been changed to be a bit more intuitive now, so maybe it doesn't require explanation?

**Comment by spong** [comment]
So I think it'd be worthwhile to have a blurb somewhere in the existing docs that describe this behavior. Something to point to when users import a rule and end up seeing alerts from a past revision like described in the bug. 

That said, not sure on where the best spot for this is. Right now we don't have dedicated `Rule Details` docs, so we'd need to fit it in with maybe the [`Manage detection alerts`](https://www.elastic.co/guide/en/security/current/alerts-ui-manage.html) page?

> View detection alerts generated by a specific rule. To do this, go to Detect → Rules, then select a rule name in the All rules table. The Rules detail page displays a comprehensive view of the rule’s details, and alert details are displayed in the Alerts table beneath the Trend histogram. Alternatively, you can go to Detect → Alerts → Manage rules, then click on a rule name in the All rules table to view the alerts associated with the rule **(including alerts from any previous or deleted revision for that specific Rule)**.

Thinking about this long-term, we're marching towards a workflow where users should be able to select different revisions of the rule through time (on Rule Details) and see what the rule looked like at that point and any associated alerts for that specific revision. Once we have that functionality I think those docs fit in well there, but for now it's more of a minor detail to their alerts workflow/rule lifecycle.

**Comment by spong** [comment]
Yup, this is effective from `8.0` going forward.

**Comment by nastasha-solomon** [comment]
Hey, @spong! Apologies for the late response. I must've missed the notification that showed @joepeeples tagging me in a comment. 

I agree that https://github.com/elastic/kibana/pull/120053 is release-note-worthy. Not only because it'll result in an observable change in the UI, but because it'll affect the way analysts triage alerts--at least that's what I assume from reading the change description. 

Just wanted to bring this up in case the PR does need to be release-noted. :) At the moment, I see that it's still labeled to be skipped, so our release notes tool won't pull it in when it generates a list of PRs to release note for 8.0.

**Comment by spong** [comment]
Thanks for the feedback @nastasha-solomon! 🙂 

I went ahead and updated the title of  https://github.com/elastic/kibana/pull/120053 to `Updates Rule Details to show all historical alerts for a given Rule` and tagged with `release_note:feature`, so now we'll have coverage in the release notes as well .
