### ISSUE TITLE
[DOCS] Update Hosts and Network page screenshots to include new data views

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1401]
We have a number of images on the Hosts and Network pages that need to include the new "data views". 

Example: 
![2022-01-19_12-57-51](https://user-images.githubusercontent.com/57149392/150192329-538333d6-c7e7-44cf-b0e9-97df7a81a249.png)

We need to ensure the .pngs and .gifs are all updated accordingly. You can likely do "Snagit Magic" with the majority of these, sans the gif.

**Comment by joepeeples** [comment]
FYI, a few of these are already updated in https://github.com/elastic/security-docs/pull/1397 (currently not yet merged):

- collapse-side-nav-button.gif — Animated GIF of sidebar expand/hide
- overview-pg.png — Overview page
- live-feed-ov-page.png — Overview page with live feed highlighted
- alert-page.png — Alerts page
- exceptions-page.png — Exceptions page

On the last two, I cropped out the sidebar and top toolbars, since those are common to all pages and maybe this could help with future maintenance. Review is still open on that PR so if we'd rather keep those elements I can re-do my images.
