### ISSUE TITLE
[BUG] Updates needed to the Actions API topic 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1497]
Need to make two changes to the [actions API topic](https://www.elastic.co/guide/en/security/master/actions-api-overview.html):

In the section that describes the external APIs Elastic Security uses to send cases, need to:
 - [ ]  Remove the old entry for `ServiceNow` and add bullets for `ServiceNow SecOps` and `ServiceNow ITSM`. Both SN connectors started using the [Import Set API](https://developer.servicenow.com/dev.do#!/reference/api/rome/rest/c_ImportSetAPI) in `7.16`. Backport this change to `7.16`. 
 -  [ ] Point to [pre-reqs](https://www.elastic.co/guide/en/security/master/post-upgrade-deprecated-sn-connector.html#pre-req-deprecated-sn-connector) to using the SN SecOps and ITSM connectors in 7.16.  Backport this change to `7.16`. 

cc: @cnasikas

**Comment by cnasikas** [comment]
The ServiceNow connector has been renamed to ServiceNow ITSM because the ServiceNow SecOps was introduced in 7.12 for detections. In cases, it was enabled in 7.16. Both of them were deprecated in 7.16 but they keep having the same name. What is deprecated is the way they interact with ServiceNow and on in Kibana. To not confuse more 🙂 what you have in the first item is correct. On the second item, I think it make sense to mentioned (or link to somewhere) that the Elastic applications are avaivable and needed to be able to create the connectors.
