### ISSUE TITLE
[BUG] Information that Run Osquery option will work on Active Hosts is not present.

### ISSUE THREAD

**Issue by arvindersingh-qasource** [elastic/security-docs#1866]
**Describe the bug**
Information that ( ```Run Osquery``` option will work on ```Active``` Hosts and if Host is Inactive `Run Osquery` option will not work ) is not present in Kibana Documentation.

**Guide Link**
https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

**Steps**
1. Open Kibana Docs for Os query Module with link - https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html
2. Scroll down to ```Run Osquery``` section.
3. Observe that it is not mentioned anywhere on the document that user will not be able to Run Osquery on an Inactive host 

**Actual Result**
![1](https://user-images.githubusercontent.com/78947943/164417949-2fa3a4df-18fc-48ee-bd91-85dd7a02593b.png)

**Expected Results**
A note must be present that ``` Host must be in Active state to use Run Osquery option```.

**Comment by arvindersingh-qasource** [comment]
@manishgupta-qasource  Please review this bug.

Thanks.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this @arvindersingh-qasource! I had noticed this prompt as well, but initially decided against documenting it since the message is already fairly descriptive. Taking another look at this, I do actually think it'd be worth documenting but with additional instructions for enabling the agent or troubleshooting it. @jmikell821 I was thinking about pointing them towards this troubleshooting guide in the Fleet docs. WDYT?
https://www.elastic.co/guide/en/fleet/current/troubleshooting-intro.html

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon 

We have validated this ticket with updated Kibana 8.2.0 Documentation and found that issue is now **fixed** and required information is present on documentation.
### Please find the below observations
#### Kibana Guide Link 
https://security-docs_1836.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html

#### Screenshot
![1](https://user-images.githubusercontent.com/78947943/165244788-f61ca43d-7ea9-4214-9f43-e9745f17bceb.png)

Hence, we are closing this ticket.

Thanks.
