### ISSUE TITLE
[BUG] The deprecations section has the wrong text

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#1874]
**Description**: 
The deprecations section has the wrong text

**URL link or topic name**: 
- https://security-docs_1828.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.2.0.html#deprecations-8.2.0

**Screenshots**:
- Actual:
Text written as: `The following endpoints are deprecated ([#129448](https://github.com/elastic/kibana/pull/129448)) and will be removed in a future release`
![image](https://user-images.githubusercontent.com/60252716/164420881-17e44a8b-986f-41bf-8945-3fda5f321a93.png)

- Expected:
The text should have mentioned of APIs instead of endpoints because the issue added is for deprecation of bulk APIs

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for the suggestion @muskangulati-qasource ! I discussed the term change with the PR owner @banderror and am leaning towards keeping the summary as is. In this particular situation, the API's endpoints are being listed individually instead of being referred to collectively as the "bulk action API" so I think "endpoints" is the more accurate term to use for the release notes summary.

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Thank you for the update.

We are closing this issue as it's written as expected.

Thanks!
