### ISSUE TITLE
[BUG] Old Search bar for Rule and Rule Monitoring page

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1876]
**Describe the bug**

Old Search bar for Rule and Rule Monitoring page

**Actual Result and Guide links**

- Rule Monitoring tab: https://security-docs_1845.docs-preview.app.elstc.co/guide/en/security/master/alerts-ui-monitor.html#alerts-ui-monitor

![image](https://user-images.githubusercontent.com/59917825/164422015-605759e7-4d9b-4d4d-b539-b7b94bdddb72.png)

- Rule tab : https://security-docs_1809.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#rules-page

![image](https://user-images.githubusercontent.com/59917825/164422128-dfcb23b9-1502-4e3b-8bc5-a49846beea6f.png)

**Expected Result:**

- Rule Monitoring tab

![image](https://user-images.githubusercontent.com/59917825/164421574-8110ba81-f484-458b-9f41-f98b56c9b2a3.png)

- Rule tab 

![image](https://user-images.githubusercontent.com/59917825/164421878-0139e11c-ed43-424c-a964-2e54d83875c1.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this @karanbirsingh-qasource ! I believe @joepeeples has made this change in https://github.com/elastic/security-docs/pull/1843 (see the third bullet in the PR description).

**Comment by joepeeples** [comment]
> Thanks for filing this @karanbirsingh-qasource ! I believe @joepeeples has made this change in #1843 (see the third bullet in the PR description).

Correct, once #1843 is merged, the screenshots mentioned above will be updated with the new search bar.

**Comment by karanverma-qasource** [comment]
Hi @nastasha-solomon & @joepeeples ,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is now fixed. 🟢

**Screenshot**

[Manage detection rules](https://security-docs_1843.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-management.html)
 
![image](https://user-images.githubusercontent.com/91867110/165042867-0f1a74c5-2a1e-44d4-8992-3949aeaf4738.png)

[Monitor and troubleshoot rule executions](https://security-docs_1843.docs-preview.app.elstc.co/guide/en/security/master/alerts-ui-monitor.html)

![image](https://user-images.githubusercontent.com/91867110/165042980-08dd489a-2724-4726-8149-b95259a0206b.png)

[Elastic Security UI | Rules page](https://security-docs_1843.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#rules-page)

![image](https://user-images.githubusercontent.com/91867110/165043342-ebd50805-c63f-418f-868a-5e15f4dac9ff.png)

[Create a detection rule](https://security-docs_1843.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html)

![image](https://user-images.githubusercontent.com/91867110/165044159-08186504-0978-4917-8363-7955960ce46a.png)

Hence, we are closing this issue and marking it as 'QA Validated'.

Thanks!!
