### ISSUE TITLE
[BUG] Analyzer and Session tab are shown enabled in Screen-shoot

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1877]
**Describe the bug**
Analyzer and Session tab are shown enabled in Screen-shoot, However they only get enabled on clicking on there respective icon

**Actual Result & Guide Link**
- https://security-docs_1844.docs-preview.app.elstc.co/guide/en/security/master/timelines-ui.html

![image](https://user-images.githubusercontent.com/59917825/164423905-92aafd8e-16a4-4276-bbe4-89652057550d.png)

**Expected Result**

![image](https://user-images.githubusercontent.com/59917825/164423806-4802b6d8-aa81-4ecd-8dfd-7d826af6cb36.png)

![image](https://user-images.githubusercontent.com/59917825/164424464-a005353c-52b2-4581-90e9-6eac4aa80cfa.png)

![image](https://user-images.githubusercontent.com/59917825/164424558-2d6c5d50-48f5-4f60-9df2-3a79927c95d0.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by benironside** [comment]
Thank you @karanbirsingh-qasource

This change is ready for review: https://github.com/elastic/security-docs/pull/1844

**Comment by karanverma-qasource** [comment]
Hi @benironside ,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is partially fixed. 

**Screenshot**

[Investigate events in Timeline](https://security-docs_1844.docs-preview.app.elstc.co/guide/en/security/master/timelines-ui.html)

![Annotation 2022-04-25 153005](https://user-images.githubusercontent.com/91867110/165066948-9fcf012c-6463-4fba-ac9c-a82222bbc3ca.jpg)

![Annotation 2022-04-25 153020](https://user-images.githubusercontent.com/91867110/165066961-5c843cdf-b7c7-4aec-8f9c-698de6581f03.jpg)


![Annotation 2022-04-25 153039](https://user-images.githubusercontent.com/91867110/165067023-e6ede2c3-016d-446a-a023-f0517be2397f.jpg)

Thanks!!

**Comment by benironside** [comment]
Good catch @karanverma-qasource, I have now addressed the remaining bug, as seen in https://github.com/elastic/security-docs/pull/1844/files 

Thanks again
