### ISSUE TITLE
[BUG]Missing Session Tab under Host Screen-Shoot

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1878]
**Description**
Missing Session Tab under Host Screen-Shoot

**Actual Result and Guide Link**:
- missing session tab under host page : https://security-docs_1809.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#hosts-ui

![image](https://user-images.githubusercontent.com/59917825/164425391-96de5f1b-9fa9-49da-933f-59198c8736ab.png)

**Expected Result**:

![image](https://user-images.githubusercontent.com/59917825/164425484-78ecab23-06f1-4fce-96f6-ae31efc04de8.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this @karanbirsingh-qasource ! I'll be making this update in https://github.com/elastic/security-docs/pull/1865 and will ping you here once it's ready.

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource the updated image is ready for your review at https://github.com/elastic/security-docs/pull/1865 - thanks!

**Comment by deepikakeshav-qasource** [comment]
Hi @nastasha-solomon,

Thank you for looking into our issue.

We looked into the updated docs and found that issue is now fixed. 🟢

**Screenshot**
[About Timeline templates | Create a Timeline template](https://security-docs_1865.docs-preview.app.elstc.co/guide/en/security/master/timeline-templates-ui.html#create-timeline-template)

![image](https://user-images.githubusercontent.com/61860752/165026546-749b98e0-7166-41e0-827d-5ac2515b859a.png)

[Elastic Security UI | Navigate the Elastic Security UI](https://security-docs_1865.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#timeline-tab)
![image](https://user-images.githubusercontent.com/61860752/165026570-5e282723-cfab-4539-9ce7-7aa94195557a.png)

[Elastic Security UI | Hosts page](https://security-docs_1865.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#hosts-ui)
![image](https://user-images.githubusercontent.com/61860752/165026587-c2964247-8aa6-4ca7-8852-ccf416826844.png)

[Host page](https://security-docs_1865.docs-preview.app.elstc.co/guide/en/security/master/hosts-overview.html)
![image](https://user-images.githubusercontent.com/61860752/165026611-f0bd74fc-e2b3-4826-888f-c669b8b236ee.png)

![image](https://user-images.githubusercontent.com/61860752/165026623-327621bd-53a1-463f-9aed-367455fd1495.png)


Hence, we are closing this issue and marking it as 'QA Validated'.

Thanks!!
