### ISSUE TITLE
[BUG]Missing session tab under Host Page

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#1950]
## Description 
Missing session tab under Host Page

## URL
https://www.elastic.co/guide/en/security/8.2/host-risk-score.html#_additional_places_to_visualize_host_risk_score_data

## Screen-Shoot

- **Actual Result**

![image](https://user-images.githubusercontent.com/59917825/166674084-d4bc3f50-f58a-43d0-b28a-a42e2c2dac32.png)

- **Expected Result**

![image](https://user-images.githubusercontent.com/59917825/166674134-c3eabc6c-270c-4185-85ff-413d8e27fb54.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by jmikell821** [comment]
@karanbirsingh-qasource the original screenshot is somewhat correct because the "host risk score" feature is behind a feature flag. As such, it won't appear by default. However, I believe I need to add the "Sessions (beta)" tab - I think that's included, but I'll need to access a server w/ the host risk score data. I'll try to find one.

**Comment by karanbirsingh-qasource** [comment]
agreed @jmikell821 and about the Kibana server with Host risk score data we can help in that and can share the cloud build credentials over mail with you with host risk data
