### ISSUE TITLE
[DOCS] New Rule fields: Related Integrations, Required Fields and Setup feature information is not available 

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2170]
**Description**
New Rule fields: Related Integrations, Required Fields and Setup feature information is not available 

**URL**
- https://www.elastic.co/guide/en/security/8.3/whats-new.html

![image](https://user-images.githubusercontent.com/61860752/176400953-b4930b22-8009-4045-9cd3-233cc0d4fdcc.png)  

**Ticket Link:**
[[DOCS] Update documentation to include the new Rule fields: Related Integrations, Required Fields and Setup](https://github.com/elastic/security-docs/issues/2015)

**Comment by joepeeples** [comment]
These new fields have been held back from the 8.3.0 release due to dependencies on content from another team. 

I think we can close this bug ticket for now, since the new fields are still in our backlog/roadmap ([issue](https://github.com/elastic/security-docs/issues/2015) and [draft PR](https://github.com/elastic/security-docs/pull/2069) are still open), just not ready to be documented quite yet.
