### ISSUE TITLE
[DOCS] Document bug where alerting rules created/edited in 8.2 will stop running on upgrade

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2180]
Document the bug where alerting rules that were created or edited in 8.2 will stop running on upgrade. Add this information as a known issue to the 8.3 and 8.3.1 release notes and use the [8.3.1 Kibana release notes](https://www.elastic.co/guide/en/kibana/current/release-notes-8.3.1.html#known-issues-8.3.1) as a ref point for language.

**Comment by nastasha-solomon** [comment]
Will need to complete the following doc tasks:

- [ ] Doc the bug as a known issue in the 8.3.1 and 8.3.0 release notes. Some notes on the known issue description:
  - In the workaround steps, emphasize that the user who performs the remediation action should (must?) have the Kibana roles equivalent to that of the rule editors'.
  - If relevant to the remediation steps, also mention that users can enable/disable Security detection rules and or update a rule's API key from **Stack Management** (**Stack Management -> Alerts and Insights > Rules and Connectors**).
  - Remediation steps are being investigated; the workaround is pending.
- [ ] Doc the bug as a fixed issue in the 8.3.2 release notes. 
  - Work with @jethr0null for the fixed issue description. The fix will likely only be pertinent to users who are upgrading from 8.2 and have edited or created custom (and possibly pre-built) rules in 8.2. 
 - [ ] Update the 8.3 release notes to inform users that they'll need to upgrade to 8.3.2 directly. 
   - Unsure, whether we want to phrase this as an instruction for users on 8.2 only or if this will apply to all 7.x and 8.x users.)
- [ ] Drop the link to the 8.3.1 known issues section into https://github.com/elastic/newsfeeds/pull/279. The live Security newsfeed inside the Security app will point to these release notes so users on 8.3/8.3.1 can easily find remediation steps to the issue. 
 
 cc: @jmikell821 @joepeeples @benironside

**Comment by joepeeples** [comment]
@nastasha-solomon I added an item for updating [Upgrade Elastic Security](https://www.elastic.co/guide/en/security/8.3/upgrade-intro.html).

Also, with the role item, I think it's more of a strong "should" than "must" — there are roles/privs that a user _could_ use and the rules would work again, but wouldn't necessarily be recommended (such as using superuser when a more limited admin role would still work and would better follow the principle of "least privilege").

**Comment by rylnd** [comment]
@nastasha-solomon @joepeeples I've got a little more clarity on which actions cause this bug:

- Installing prebuilt rules in 8.2
- Upgrading prebuilt rules in 8.2
- Creating/editing custom rules in 8.2
- Adding an action to a rule in 8.2

Which can effectively be summarized as "creating or modifying a rule in 8.2" but which notably includes previously-installed prebuilt rules that were upgraded in 8.2.

### Steps to remediate
The [bugfix PR](https://github.com/elastic/kibana/pull/135663) includes instructions for the Stack Rules UI:

> If a customer upgrades to 8.3.0 or 8.3.1 and their alerting rules have stopped running with an error similar to the example above, they will need to use the Update API key operation in Stack Management > Rules and Connectors to restore the alerting rule to a functional state. It should be noted that the Update API Key operation causes the alerting rule to run as the user that performed the operation.

If users wish to remediate via the Security Solution UI, it's going to involve the disabling and then re-enabling of those affected rules [^1]. Since both the gathering of affected rules and their toggling have to be done manually [^1], the recommendation isn't particularly user-friendly.

However, if ONLY custom rules are affected, users can employ a more streamlined, tag-based approach:

1. Select all affected rules and apply an identifying tag to them (e.g. "BEING FIXED")
2. Filter the rules table by this tag, and disable all rules
3. Filter the rules table by this tag, and enable all rules

[^1]: Here is a simple query that users can run BEFORE any remediation is attempted, to get a list of all affected rules:

    ```
    GET .kibana-event-log*/_search
    {
      "size": 0,
      "aggs": {
        "failing_rule_ids": {
          "terms": {
            "field": "rule.id",
            "size": 10000
          }
        }
      },
      "query": {
        "query_string": {
          "query": "Reason: missing authentication credentials for REST request, caused by \"\"",
          "fields": [
            "error.message"
          ]
        }
      }
    }
    ```

**Comment by nastasha-solomon** [comment]
Not closing this issue yet because I might still need to work with @jmikell821 to update the [Upgrade Elastic Security](https://www.elastic.co/guide/en/security/master/upgrade-intro.html) topic. I'm updating the known issue sections of 8.3.x versions for 8.3.3 in https://github.com/elastic/security-docs/pull/2202 and am encountering some formatting roadblocks so this might be an opportunity to move the content out of the release notes and into the upgrade topic.

**Comment by nastasha-solomon** [comment]
Closing as this as it's doc'd in the release notes. Will eventually move it to the upgrade guide if it's ever needed there.
