### ISSUE TITLE
[DOCS][Cases] Write Performance Improvements

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/security-docs#2206]
## Description 

The cases team improved the time required to perform write operations (creating, updating, and deleting a case, comment, or setting configurations). The operations should be improved by about half a second.

PR: https://github.com/elastic/kibana/pull/136452

## Acceptance Test Criteria

Maybe just list an item in the enhancements that we improved performance within cases.
 

## Notes

N/A

**Comment by nastasha-solomon** [comment]
@jonathan-buttner since https://github.com/elastic/kibana/pull/136452 has the ResponseOps team label, it was (correctly) pulled in the 8.4 Kibana release notes and doc'd [here](https://github.com/elastic/kibana/pull/137621/files#diff-6eabb97e98640429cb68b61823f99438d287d604d72ecf0e93ed2e9ecbec7479R183).
cc: @jmikell821 @benironside

**Comment by nastasha-solomon** [comment]
Doc'd in the 8.4.0 release notes here: https://www.elastic.co/guide/en/kibana/current/enhancements-and-bug-fixes-v8.4.0.html
