### ISSUE TITLE
[DOCS] Bulk action handling for detection rules

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#2209]
## Description 

PR https://github.com/elastic/kibana/pull/134664 enhances handling for bulk actions applied to both prebuilt and custom rules. If an action can't be performed because some of the selected rules are prebuilt rules, the error messaging and confirmation notifications will account for this, instead of a blanket error.

Also review the UI copy added, and follow up with any feedback (separate issue, ping team directly, etc.).

## Notes

- Demo of this feature included index patterns and exporting. Tags are probably also involved.
- Several of the new modals/toasts appear to capitalize "Custom rules" but should probably be lowercase.

**Comment by banderror** [comment]
> If an action can't be performed because some of the selected rules are prebuilt rules, the error messaging and confirmation notifications will account for this, instead of a blanket error.

@joepeeples To be precise, even before https://github.com/elastic/kibana/pull/134664 we were showing this modal window instead of running a bulk action that would end up with errors. You can compare the "Before" and "After" in the PR description. What the PR introduced is 2 things:

- Added proper handling for machine learning rules. Before the PR, if the user selected some custom machine learning rules and tried to edit their index patterns, we would allow them to do that and it would end up with an error. After the PR, we show this modal window where we tell them that they can't edit index patterns for machine learning rules. This is a visual change.
- Added this `dry_run` mode which is a technical improvement for our bulk editing implementation in the app. That's internal change.

> Several of the new modals/toasts appear to capitalize "Custom rules" but should probably be lowercase.

This has been done in https://github.com/elastic/kibana/pull/138077
