### ISSUE TITLE
[DOCS] Add docs for Endpoint rules

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#2390]
## Description 

We maintain and publish customer-facing docs for Elastic prebuilt detection rules for SIEM use cases, but we don't have much for Endpoint rules such as [elastic/endpoint-rules](https://github.com/elastic/endpoint-rules) (private) or [elastic/protections-artifacts](https://github.com/elastic/protections-artifacts) (public), other than repo readmes.

@Mikaayenson mentioned a need to have more docs around Endpoint rules, and he's offered add more details to this issue to guide our efforts.

**Comment by Mikaayenson** [comment]
There are differences between the two repos that might be good to highlight within docs. We highlight some in this upcoming [blog](https://docs.google.com/document/d/1trlBw68NgF0T88ytBtF3HtvQ8ujVDM5iZZPaE31mmqg/edit#heading=h.kjxrjani732v).


  | Detection Rules : URL | Endpoint Behavior : URL
-- | -- | --
Design Goals | Provide the most robust detection coverage of all threats, leveraging all data sources available. Some tuning of rules based on organization-specific environments is expected. | Provide very high confidence, prevention-focused, minimal tuning at the expense of false negatives on a per-rule basis. We want every organization to be able to enable behavior protection and have a great experience out of the box, with little tuning required.
Data Streams | Will search across all specified indexes per rule within a stack | Agent searches data on the endpoint
Engine Processing | Batch process | Real time data streaming

Also, suppose users elect to filter events on their endpoints. In this case, the detection engine can lead to false negatives because the events are dropped before being sent to elasticsearch, whereas endpoint rules process them before dropping. 

There may be other differences but having an overview of the endpoint rules which are released on https://github.com/elastic/protections-artifacts/tree/main/behavior would be great. The README there may help as well flush out these endpoint docs.

**Comment by joepeeples** [comment]
This effort is progressing in a separate/duplicate issue: https://github.com/elastic/security-docs/issues/4460
