### ISSUE TITLE
[BUG] Old screenshot under Filter out uncommon application alerts

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/security-docs#2401]
**Description**: Old screenshot under Filter out uncommon application alerts

**URL link or topic name**: 
- https://www.elastic.co/guide/en/security/8.4/tuning-detection-signals.html#filter-rule-process

**Screenshots**:
- Actual:
![image](https://user-images.githubusercontent.com/61860752/187149394-46a22da5-f3aa-4152-baa7-6eab2854cebf.png)

- Expected:
![image](https://user-images.githubusercontent.com/61860752/187149756-16797893-65c9-4405-a4bc-36ed9697d45d.png)

**Comment by joepeeples** [comment]
This screenshot bug actually uncovered several other problems on this page:

- The rule "Unusual Process Execution - Temp" was deprecated in 8.4, so we shouldn't use it as an example
- Several links are displaying incorrectly, and they're pointing to 8.3 rule docs instead of the current version. This is also related to deprecated rules, as per https://github.com/elastic/security-docs/pull/2306#issuecomment-1216660833:
> Also, you may see adjustments to the [tune-rule-signals.asciidoc](https://github.com/elastic/security-docs/blob/c56b9d00f103deb2a4a8605856748c88340ce534/docs/detections/prebuilt-rules/tune-rule-signals.asciidoc) file. This was initially causing the checks to fail because it had links to rules that we have deprecated and are no longer current for this release. As a result I adjusted the links to point to 8.3 instead of current so they are not broken for now.

**Comment by joepeeples** [comment]
Screenshot updated in #2415. Also updated some content and links as noted above.

**Comment by deepikakeshav-qasource** [comment]
Hi @joepeeples  ,

We have validate tis issue and all the required changes are present and correct. ✔️

![image](https://user-images.githubusercontent.com/61860752/188368249-3ff8ef0e-e181-49ca-8edf-8e42f4be475d.png)

Hence, we are marking as QA Validated!!
