### ISSUE TITLE
[BUG]: Steps need to be re-sequenced for Save later queries for future use.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/security-docs#2612]
**Description:**
Steps need to be re-sequenced for Save later queries for future use:
- User once has to Submit and then Save for later button is activated.

**PR Ticket:**
https://github.com/elastic/security-docs/pull/2561

**URL link or topic name:**
https://security-docs_2561.docs-preview.app.elstc.co/guide/en/security/master/invest-guide-run-osquery.html#run-live-queries-ig
https://security-docs_2561.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html#alerts-run-osquery

**Screenshots/ Recordings:**
**Expected:**

https://user-images.githubusercontent.com/77374876/196629326-a391cd4e-0241-4318-9254-ac33edece779.mp4

**Actual:**

![11](https://user-images.githubusercontent.com/77374876/196622434-0dfd66d7-ba71-4da2-b9d5-1e6840cbebd8.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for catching this, @amolnater-qasource ! I made the fix in https://github.com/elastic/security-docs/pull/2561. Please take a look when you hav a chance, thanks!

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/security-docs/pull/2561

**Comment by arvindersingh-qasource** [comment]
Hi @nastasha-solomon ,

Thanks for looking into the issue.

We have validated this issue on the `Kibana Guide [8.5]` and found that issue is **Fixed**.

#### Guide Link
 - https://www.elastic.co/guide/en/security/8.5/invest-guide-run-osquery.html

### Please find the below observations
![3](https://user-images.githubusercontent.com/106220189/199467934-667809a1-4dbb-417c-a293-98ec89baf7ac.PNG)


Thanks
