### ISSUE TITLE
Add information that exception also apply for threat indecies in Indicator Match rule

### ISSUE THREAD

**Issue by nkhristinin** [elastic/security-docs#2999]
## Description 
Add information that exceptions also apply for threat indecies in the Indicator Match rule

To this page 
https://www.elastic.co/guide/en/security/master/add-exceptions.html
So, this exception will filter out not only events from the source, but also documents from the threat index.
<img width="633" alt="Screenshot 2023-02-16 at 16 31 03" src="https://user-images.githubusercontent.com/7609147/219411836-5a0903bd-faa1-4f00-97d9-3d29388545d6.png">

<img width="1082" alt="Screenshot 2023-02-16 at 16 30 32" src="https://user-images.githubusercontent.com/7609147/219411714-e07f50cc-e1fb-4a63-b106-e2df60685dd0.png">

**Comment by nastasha-solomon** [comment]
@nkhristinin for the text, would something like the following be accurate:

> Be careful when adding exceptions to [indicator match rules](https://www.elastic.co/guide/en/security/master/rules-ui-create.html#create-indicator-rule) rules. Exceptions are evaluated against source and indicator indices, and when the exception matches events in _either_ indices, alerts are not generated. 

Should we also recommend to tweak the rule's custom query so that it doesn't accidentally filter out threat fields that are present in the source or indicator indices? If yes, what should users do to prevent this? For example, should they add filters (for threat fields they want to throw alerts for) to the rule's custom query or use specific syntax in the query?

**Comment by nkhristinin** [comment]
The text looks good to me.
About suggestion, they can use query of filters for source/threat indices, but it does not cover all features of exception, so it will not help in 100% cases
