### ISSUE TITLE
Add ETag information to self-hosted artifact sections

### ISSUE THREAD

**Issue by nfritts** [elastic/security-docs#3429]
## Description 

as part of [this SDH](https://github.com/elastic/sdh-endpoint/issues/282) we noticed that the documentation [here](https://www.elastic.co/guide/en/security/current/offline-endpoint.html#air-gapped-artifact-server) could probably be improved.  its very important that a customer hosted artifact mirror/proxy set the ETag header.   It doesn't actually say that in the documentation, we only show it being set in the example configs we provide (with a note that the config isn't appropriate for production environments).   We should definitely mention that the ETag header needs to be set.

**Comment by nastasha-solomon** [comment]
Notes from Slack convo with @nfritts:
- The ETag header is an identifier for a specific version of a resource.  Endpoint uses it to tell if the artifacts have been updated since it last downloaded them.  If there is no ETag header, it doesn't download new artifacts.
- The ETag should be generated by the user's http server. It being generated is dependent on the web server.

cc: @roxana-gheorghe
