### ISSUE TITLE
[Bug] Screenshot needs to be updated for the missing ES|QL tab in timeline

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#4223]
**Description**:
Screenshot needs to be updated for the missing ES|QL tab in timeline

**URL link or topic name**:
- https://www.elastic.co/guide/en/security/8.11/indicators-of-compromise.html#find-related-sec-events
- https://www.elastic.co/guide/en/security/8.11/timelines-ui.html

**Screenshots**:
- Actual:

![Actual](https://github.com/elastic/endgame-platform/assets/60252716/c0c31853-032b-49dc-8e26-cb6e22105555)

- Expected:

![Exppected](https://github.com/elastic/endgame-platform/assets/60252716/8df78ff3-cf7d-46c9-b11f-04e17de9235f)

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @karanbirsingh-qasource! The fix is ready at https://github.com/elastic/security-docs/pull/4497 when you have a chance to validate it.

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @karanbirsingh-qasource! Please see my notes below:

- The 8.11 updates to the ESS docs are ready for review at https://github.com/elastic/security-docs/pull/4498.
- The 8.12 updates to the ESS docs are partially completed:
   - Timeline docs are being refreshed at https://github.com/elastic/security-docs/pull/4483 and I'll be merging this PR tomorrow. 
   - Updating the 8.12 docs might take a bit longer because I'll need some assistance recreating [this image](https://www.elastic.co/guide/en/security/8.12/images/indicator-in-timeline.png). Any help you can provide here would be much appreciated!

**Comment by karanbirsingh-qasource** [comment]
Hi @nastasha-solomon 

thanks for sharing the update and we have reviewed the fixed pr and below we have attached the requested screenshot for indicator of compromise.

**new screen-shot**

file.hash.sha256: "116dd9071887611c19c24aedde270285a4cf97157b846e6343407cf3bcec115a"

threat.indicator.file.hash.sha256: "116dd9071887611c19c24aedde270285a4cf97157b846e6343407cf3bcec115a"

![image](https://github.com/elastic/security-docs/assets/59917825/8c70e739-01a5-421a-a8a9-89d09349a5be)

**old screen-shot**

![image](https://github.com/elastic/security-docs/assets/59917825/465b80f3-db7d-402d-b9bf-640cb751c8c0)


Hope it resolved your request
