### ISSUE TITLE
Timeline docs should be updated with the new UI.

### ISSUE THREAD

**Issue by logeekal** [elastic/security-docs#4306]
## Description 

Security solution is coming up with minor changes in the Timeline UI and all the changes have been covered in:

- https://github.com/elastic/kibana/pull/168230.
- https://github.com/elastic/kibana/pull/172030

All the UI modifications are listed in the PR description. Please reach out to me if you some issue or you have some questions.

These Changes are coming in both Serverless and ESS in 8.12 release.

**Comment by logeekal** [comment]
@nastasha-solomon , updated the tour PR link.

**Comment by nastasha-solomon** [comment]
UI copy work review being tracked in https://github.com/elastic/security-docs/issues/4369. The issue linked in this issue's description (https://github.com/elastic/kibana/pull/172030) tracks the implementation of the tour.

**Comment by nastasha-solomon** [comment]
### Serverless doc updates:

Updates to the [Investigate events in Timeline](https://docs.elastic.co/serverless/security/timelines-ui) page:
- Intro
   - [ ] Might need to mention the collapsed query builder in the second para. 
   - [ ] Refresh [`-events-timeline-ui-updated.png`](https://docs.elastic.co/ZWxhc3RpYy93b3JkbGFrZS1zdGFnaW5n/staging-serverless-security-docs/docs/images/timelines-ui/-events-timeline-ui-updated.png). Note that KPIs have been removed in 8.12. They might be redesigned and re-added in 8.13.
   - [ ] Briefly describe how unsaved and recently saved Timeline are portrayed. Can update the sentence under the screenshot.
   
- [View and refine Timeline results](https://docs.elastic.co/serverless/security/timelines-ui#view-and-refine-timeline-results)
    - [ ] Update the last sentence that says "click **Data view** to the right of the date and time picker".
    - [ ] Refresh [`-events-timeline-ui-renderer.png`](https://docs.elastic.co/ZWxhc3RpYy93b3JkbGFrZS1zdGFnaW5n/staging-serverless-security-docs/docs/images/timelines-ui/-events-timeline-ui-renderer.png). The query bar and associated elements have been updated. 
- Edit existing filters
   - [ ] Refresh [`-events-timeline-ui-filter-options.png`](https://docs.elastic.co/ZWxhc3RpYy93b3JkbGFrZS1zdGFnaW5n/staging-serverless-security-docs/docs/images/timelines-ui/-events-timeline-ui-filter-options.png). The icon on the left side of the menu and for the **Load saved query** option has changed.
- Filter Timeline results with EQL
   - [ ] Refresh [`-events-correlation-tab-eql-query.png`](https://docs.elastic.co/ZWxhc3RpYy93b3JkbGFrZS1zdGFnaW5n/staging-serverless-security-docs/docs/images/timelines-ui/-events-correlation-tab-eql-query.png) 

New or modified functionality that's not doc'd and needs to be added to the Investigate events in Timeline page:

<img width="800" alt="timeline-design-updates" src="https://github.com/elastic/security-docs/assets/79124755/40452332-1874-438f-a55e-d22140017d6d">

- **Favorites button** - This button was accompanied by text (see image of 8.11 design above) in 8.11 and earlier. In 8.12, the favorite button is the [starEmpty icon](https://eui.elastic.co/#/display/icons) to the right of the Timeline title. By clicking the star, users can favorite or unfavorite a Timeline. 
  - [ ] Repurpose the tip at the start of the page and use it to describe the favoriting feature. Really don't need to mention the attach to case functionality as a "tip" when there's a whole [section](https://docs.elastic.co/serverless/security/timelines-ui#attach-timeline-to-a-case) on this further down.
- **Create new and open existing Timeline buttons** - These only existed on the main Timeline main page in 8.11, so they'll need to be doc'd for 8.12. 
  - [ ] Create a new section above [Attach a Timeline to a case](https://docs.elastic.co/serverless/security/timelines-ui#attach-timeline-to-a-case). Name the new section: Create new or open existing Timelines
     <img width="250" alt="Screenshot 2023-12-02 at 2 34 28 PM" src="https://github.com/elastic/security-docs/assets/79124755/b7d5e891-c287-4be4-9d44-6ecc119e7ca1">
- **Collapse and expand query builder button** - This is net new functionality. 
   - [ ]Add a line about the default state of the query builder to the [Narrow or expand your KQL query](https://docs.elastic.co/serverless/security/timelines-ui#narrow-or-expand-your-kql-query) section. Also explain where to find the button because it's not labeled in the UI -- it's a button with the Timeline icon in the center. When users hover over the button, a tooltip with instructions of how to use the button appears. 
- **Time range lock button** - Need a description for this.

Updates to the [Create Timeline templates
](https://docs.elastic.co/serverless/security/timeline-templates-ui) page:
- Refresh the following screenshots:
  - [ ] [`-events-create-template-ui.png`](https://docs.elastic.co/ZWxhc3RpYy93b3JkbGFrZS1zdGFnaW5n/staging-serverless-security-docs/docs/images/timeline-templates-ui/-events-create-template-ui.png)
  - [ ] [`-events-create-a-timeline-filter.png`](https://docs.elastic.co/ZWxhc3RpYy93b3JkbGFrZS1zdGFnaW5n/staging-serverless-security-docs/docs/images/timeline-templates-ui/-events-create-a-timeline-filter.png)
     
Misc. improvements:

- Add an icon wherever the **All actions** menu is referenced throughout the [Investigate events in Timeline](https://docs.elastic.co/serverless/security/timelines-ui) page. If end up doing this, might need to do the same for the ESS docs to ensure parity between the docsets. This is a nice to have, not a need to have.

**Comment by nastasha-solomon** [comment]
Thanks for the additional notes, @logeekal! I expanded the list of doc updates to include the updates needed to the [Timeline schema](https://docs.elastic.co/serverless/security/timeline-object-schema#timeline-object-columns) page and will check in with you tomorrow on design decisions made about the favorites button and expand/collapse query builder button.

RE your question about the section title:
> [This](https://docs.elastic.co/serverless/security/timelines-ui#narrow-or-expand-your-kql-query) heading states Narrow or expand your KQL query but it talks about query filters. Should we rename it to just query instead of KQL Query?

Does the query builder use KQL or is it using a different query language? I always thought it was a visual representation of the text-based KQL query bar above it, but maybe I'm wrong?

**Comment by logeekal** [comment]
Hey @nastasha-solomon ,

Below are my responses.

>[Filter Timeline results with EQL](https://docs.elastic.co/serverless/security/timelines-ui#filter-timeline-results-with-eql)
>
>Refresh [-events-correlation-tab-eql-query.png](https://docs.elastic.co/ZWxhc3RpYy93b3JkbGFrZS1zdGFnaW5n/staging-serverless-security-docs/docs/images/timelines-ui/-events-correlation-tab-eql-query.png)

Below is the replacement screenshot : 
![Screenshot 2023-12-07 at 12 35 32](https://github.com/elastic/security-docs/assets/7485038/4de3f842-c6ca-480c-a0e1-2ee5b028697f)

>Does the query builder use KQL or is it using a different query language? I always thought it was a visual representation of the text-based KQL query bar above it, but maybe I'm wrong?

I would say, it is a subset of KQL but not exactly KQL. It cannot do `NOT ( ... complete query )` which can be done in KQL. I will ask team today for confirmation and get back to you.

**Comment by nastasha-solomon** [comment]
https://github.com/elastic/kibana/pull/173015 introduces some additional UI changes that'll impact screenshots and potentially instructions for opening an existing Timeline, creating a new Timeline, and creating a new Timeline template. 

I plan to lump the newest UI changes into https://github.com/elastic/staging-serverless-security-docs/pull/240 so I can consolidate everything into a single docs PR.

**Comment by logeekal** [comment]
@nastasha-solomon , I have updated the EQL screenshot in above comment. So you can take from there directly.

**Comment by nastasha-solomon** [comment]
Noticed a handful of additional screenshots that need to be refreshed. Adding them to [the list](https://github.com/elastic/security-docs/issues/4306#issuecomment-1837242311) and committing them to the ESS and Serverless doc PRs.
