### ISSUE TITLE
[Known Issue] Add docs to describe a known issue/limitation of EQL rule cross-cluster search

### ISSUE THREAD

**Issue by e40pud** [elastic/security-docs#4744]
### Description

We've got a complain from customer that security solution EQL rule fails when they try to use multiple remote clusters as indices.

Security EQL rule failing with:
> security_exception: action [internal:transport/proxy/indices:data/read/search[phase/query]] is unauthorized for API key id [...] of user [example-user1] on indices [example-index1], this action is granted by the index privileges [read_cross_cluster,all]

After investigation we realised that:
- the issue happens in all versions prior to `8.12` where EQL rules are available
- the issue was fixed in `8.12+`
- the issue happens when user tries to use two or more different cluster, including combination of the local and remote clusters
- the issue does not happen if rule has been created by the `superuser`

We would like to add docs describing this limitation as a known issue.

### Area/Engineering team

Detections & Response

### Which documentation set does this known issue impact?

ESS and serverless

### Affected versions

Version from `7.14.0` to `8.12.0` (not including `8.12.0`).

### Workaround

As a workaround, users can update the API key of the rule via updating the rule with the superuser. Here are the steps how to do that https://www.elastic.co/guide/en/security/current/rules-cross-cluster-search.html#update-api-key

**Comment by nastasha-solomon** [comment]
Hey, @e40pud! Thanks for filing this and apologies for the late reply. Seeing that this exists in the product from 7.17-8.11, I think it'd make sense to describe the limitation and its workaround in the following rule docs instead of release notes. 
- [Create an event correlation rule](https://www.elastic.co/guide/en/security/8.11/rules-ui-create.html#create-eql-rule)
- [Cross-cluster search and detection rules](https://www.elastic.co/guide/en/security/8.11/rules-cross-cluster-search.html) - Note that this page is only available from 8.6-8.12, so I'll need to link users to [these Kibana docs](https://www.elastic.co/guide/en/kibana/8.5/alerting-setup.html#alerting-authorization) that describe the same steps for updating a rule's API key.

Placing here ensures that the information is visible and present as users work through the steps of creating an EQL rule. Let me know if this works and if you have any concerns about this approach. Thanks!

**Comment by e40pud** [comment]
I feel like with this message we tell user that it is kind of expected behaviour and that they should promote users to superusers to use CCS functionality in EQL rules. I think it might be better to say that there is a known issue which prevents users from using multiple clusters in EQL rules and that there is a workaround where superuser role can update existing problematic EQL rules and that will update API key to superuser privileges and allow CCS.

What do you think @nastasha-solomon?

**Comment by nastasha-solomon** [comment]
Sure, how does this look, @e40pud ? 

> EQL rules have a limitation that prevents them from querying multiple indices from different clusters (local and remote). To workaround this known issue, a user with the `superuser` role must modify the EQL rules that are configured to use cross-cluster search. Doing this updates the rule's API key to use `superuser` privileges.  

This would be added as a note to the docs I mentioned [here](https://github.com/elastic/security-docs/issues/4744#issuecomment-1926101579).

**Comment by e40pud** [comment]
This looks great, thank you!

**Comment by nastasha-solomon** [comment]
There's no need to doc this in the Serverless docs as this bug was fixed in `8.12` and `main`.
