### ISSUE TITLE
[DOCS] Add an EQL Query in the Timeline

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#541]
As a user of the timeline, I would like to be able to write an EQL query in the timeline and see the different sequences from this query.

Related issue: https://github.com/elastic/security-team/issues/454
Pull request: https://github.com/elastic/kibana/pull/90816

EQL Overview [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql.html). 

Note: We'll likely need to update screenshots since there's a new **Correlation** tab in the Timeline UI. 

![image](https://user-images.githubusercontent.com/57149392/110526938-64faf800-80e4-11eb-88c5-fb02851790b5.png)

**Comment by nastasha-solomon** [comment]
Since this feature offers users a new way to query and view events and alerts, I think the [Investigating events in Timeline](https://www.elastic.co/guide/en/security/current/timelines-ui.html#timelines-ui) topic is the most appropriate place to document it. Fortunately, the topic only has two screenshots that need to be updated and, if the docs should describe feature functionality only, I can insert the new feature docs into the “Narrow or expand your query” section. 

Within this section, or perhaps in a separate sub-section, I was thinking it could be also useful to include a couple of lines that describe when to use KQL or EQL queries and how to read the results that are returned. I'm not sure whether this would be too much information for results returned by a KQL query, but do think it's necessary for EQL query results because the results are color-coded to indicate groupings (and sequences?) and this detail is not clarified anywhere within the UI.

There's obviously more to document about the new Correlation tab, but I wanted to share this with you (@jmikell821 and @DonNateR ) if you think there’s a better way to frame and organize these new feature docs. Looking forward to any feedback you might have and thanks in advance for your help!

**Comment by nastasha-solomon** [comment]
Completed reviews and merged PR (#544). Changes have also been backported to 7.x and 7.12.
