### ISSUE TITLE
[Security Solution] Old Timeline Component instead of Discovery in Timeline Doc

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/security-docs#5692]
**URL**

https://www.elastic.co/guide/en/security/8.15/es-ui-overview.html#draggable-timeline-elements

https://www.elastic.co/guide/en/security/8.15/indicators-of-compromise.html#find-related-sec-events

**Actual Result** 

![image](https://github.com/user-attachments/assets/0a44e848-8f65-424a-8bed-83526f600a9d)

![image](https://github.com/user-attachments/assets/d2da0e97-fec1-4f5a-bb84-a790a3e58eff)

**Expected Result**

![image](https://github.com/user-attachments/assets/2eb21917-4f33-4a54-9bfd-f3dfc7ccfde6)

**Comment by amolnater-qasource** [comment]
Reviewed & assigned to @jmikell821

**Comment by nastasha-solomon** [comment]
Thanks for filing this, @karanbirsingh-qasource! In addition to the drag-and-drop functionality that you highlighted in the issue description, I tested all of the other accessibility features that we doc'd on the Elastic Security UI page and noticed the following: 

(cc'ing @logeekal in case any of these are bugs)

- The drag-and-drop functionality only works with the mouse (see the first part of the gif below). It doesn't work if you follow the doc'd instructions of selecting a field and then pressing the spacebar. The spacebar actually scrolls through the page, as demo'ed in the gif below:
   ![spacebar-drag-n-drop](https://github.com/user-attachments/assets/baa5e0ee-24f4-4c50-8230-372ecbd93d92)
- I'm not sure whether our hotkey shortcuts (`f`, `o`, `a`, `t`, and `c`) work anymore. I was able to open a cell's menu and navigate through the menu options using the `Enter` + `Tab` combo, but didn't see the hotkey shortcuts when I was doing so. See an example [here](https://github.com/elastic/security-docs/pull/5700/files#diff-93e2dc7ca99745bc852e5a77ca05659e29eb698e508b7a03cfb14f37952d13b9).
- I was unable to move between event fields using the `Shift` key and directional arrows, which is what we have doc'd in the third bullet [here](https://www.elastic.co/guide/en/security/master/es-ui-overview.html#draggable-timeline-elements). Similarly, the `Shift` + `Tab` combo didn't work. 
- The following features only worked if row renderers were turned off:
   - Using `CTRL` + `Home` to shift keyboard focus to the first cell in a row and `CTRL` + `End` to move keyboard focus to the last cell in the row.
   - Using the `Page Up` and `Page Down` keys to scroll through the page.

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource except for the following gifs, the outdated gifs and images in the docs for UI accessibility features and indicators of compromise are updated. The [notes above](https://github.com/elastic/security-docs/issues/5692#issuecomment-2284892415) explain why I was unable to update them in the ESS and Serverless docs:
- [`timeline-ui-accessiblity-drag-n-drop.gif`](https://security-docs_bk_5700.docs-preview.app.elstc.co/guide/en/security/master/images/timeline-ui-accessiblity-drag-n-drop.gif)
- [`timeline-accessiblity-event-renderers.gif`](https://security-docs_bk_5700.docs-preview.app.elstc.co/guide/en/security/master/images/timeline-accessiblity-event-renderers.gif)

**Comment by logeekal** [comment]
@nastasha-solomon 

>The drag-and-drop functionality only works with the mouse (see the first part of the gif below). It doesn't work if you follow the doc'd instructions of selecting a field and then pressing the spacebar. The spacebar actually scrolls through the page, as demo'ed in the gif below:

Yes it is correct and i see that i has not beed working for a while. For example in `8.14` as well it is not accessible with keyboard.


>I'm not sure whether our hotkey shortcuts (f, o, a, t, and c) work anymore. I was able to open a cell's menu and navigate through the menu options using the Enter + Tab combo, but didn't see the hotkey shortcuts when I was doing so. See an example [here](https://github.com/elastic/security-docs/pull/5700/files#diff-93e2dc7ca99745bc852e5a77ca05659e29eb698e508b7a03cfb14f37952d13b9).

Nope, same. They have not been working for a while. We can talk whether this needs to be re-added.

>I was unable to move between event fields using the Shift key and directional arrows, which is what we have doc'd in the third bullet [here](https://www.elastic.co/guide/en/security/master/es-ui-overview.html#draggable-timeline-elements). Similarly, the Shift + Tab combo didn't work.

I am able to do that as demonstrated below

https://github.com/user-attachments/assets/9e0f2d06-4c3b-4777-bbfc-7429c3245fd6


> - Using CTRL + Home to shift keyboard focus to the first cell in a row and CTRL + End to move keyboard focus to the last cell in the row
>  - Using the Page Up and Page Down keys to scroll through the page


This seems to be working as well with and without row-renderers as shown below. What you will notice is that with Row Renderers the last column that is focused is that `Row Renderer` row. It is because it is technically the last column.


https://github.com/user-attachments/assets/71d6d787-06c7-4d8e-9651-337085f1331d

Let me know if you have any questions.

**Comment by nastasha-solomon** [comment]
Thanks for taking a look at these, @logeekal! Couple of follow-up questions and responses for you below:

- I'm not sure who'd make the decision about re-adding the drag-and-drop functionality and hot keys. I'm happy to discuss it with you, but I imagine someone from the Product or Eng team would need to make the final call on whether to re-add it. In the meantime, it might make sense to remove the docs that describe how it work since they're no longer correct.  
- Using the `Shift` key and directional arrows, were you able to do the following:

    > If an event has an event renderer, press the `Shift` key and the down directional arrow to apply keyboard focus to the event renderer and `Tab` or `Shift + Tab` to navigate between fields. To return to the cells in the current row, press the up directional arrow. To move to the next row, press the down directional arrow.
    
    I was mostly able to move between elements in the table (field names, menus, etc.) using the doc'd instructions, but it wasn't working for me when I tried navigating through event fields in the rendered view. 

- Thanks for clarifying that the event rendered view is technically the last column in a row if it's displayed. Because the event rendered view always appears underneath the non-event rendered view, I wasn't sure whether both views made a single row or if they were two separate rows within the same row. I had also thought the event rendered view was the start of a new row because you can apply focus around the entire rendered view, like so:
    <img width="800" alt="Screenshot 2024-08-13 at 9 46 52 AM" src="https://github.com/user-attachments/assets/d9d37705-6680-4cf7-9d79-f18a148a1a8f">
- Glad to see that the page up/down function works without row renderers! :)
