### ISSUE TITLE
[BUG]Update Screenshot in Response Console Help Section to Include 'Scan Response' Option

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/security-docs#5694]
### Documentation links

https://www.elastic.co/guide/en/security/current/response-actions.html

### Description

Old Screenshot is present on which `scan` response is not present

### Screenshot 

- **Actual**

![image](https://github.com/user-attachments/assets/3a2b37fe-a15e-4afa-8817-eac049392411)

- **Expected**

![image](https://github.com/user-attachments/assets/fc985b16-66cf-43cf-a4bc-808f3bb185cc)

**Comment by sukhwindersingh-qasource** [comment]
Hi @muskangulati-qasource 
Kindly review this
Thanks!

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @jmikell821

**Comment by joepeeples** [comment]
We can bundle this into https://github.com/elastic/security-docs/pull/5566, which is adding `scan` to serverless docs. I'll add a new commit to update the image on both serverless and ESS sides.

**Comment by ashokaditya** [comment]
Thanks @joepeeples for taking care of this.

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

Thank you for looking into our issue.

We validated the issue against the updated docs and found the issue is now fixed. 🟢 

**Screenshot**:
![image](https://github.com/user-attachments/assets/24d8f60d-8008-4601-b91b-f649af026a89)

Hence, we are marking this issue as 'QA Validated'.

Thanks!
