### ISSUE TITLE
[DOCS IA] Remove technical preview section

### ISSUE THREAD

**Issue by benironside** [elastic/security-docs#5712]
UPDATE 8/30: We are going to keep the Troubleshooting section for now. Updating the action items. 

### Description

As part of the Sec Docs IA [meta issue](https://github.com/elastic/docs-projects/issues/236), remove the Technical preview sections from the ESS docs IA.  

These changes are described in the [IA outline](https://docs.google.com/document/d/1TJ-0W1agfywm22dVD4JqID3NHYwxny-s9U3kafqle3A/edit):
- The pages in the technical preview section have become outdated and should be removed.

### Which documentation set does this change impact?

ESS only

### ESS release

8.14

### Serverless release

As soon as possible.

**Comment by nastasha-solomon** [comment]
The CI checks in 5747 failed after I [deleted](https://github.com/elastic/security-docs/pull/5747/files#diff-b731536428f66dafb8db9fea01f433efb33a731dfd2598ca8bd76bcedf7cc041) the  `troubleshooting-intro.asciidoc` file from the Security docs dir because the page/file is being referenced [in a separate docset](https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/current/troubleshooting-and-faqs.html). Here was the error message that was returned:

`````
INFO:build_docs:Bad cross-document links:
--
  | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/starting-with-the-elasticsearch-platform-and-its-solutions/master/troubleshooting-and-faqs.html contains broken links to:
  | INFO:build_docs:   - en/security/master/troubleshooting-ov.html

`````

There's a few ways that we can go about resolving this, but ultimately, we need to ensure that the [Elastic Security troubleshooting](https://www.elastic.co/guide/en/security/8.15/troubleshooting-ov.html) link in the "Starting with the Elasticsearch Platform and its Solutions" docs properly resolves or doesn't exist (i.e., we remove the reference) _before_ we delete the `troubleshooting-intro.asciidoc` file from the Security docs.

**Comment by nastasha-solomon** [comment]
Removing reference to page:

- https://github.com/elastic/tech-content/issues/474
- https://github.com/elastic/tech-content/pull/475

**Comment by nastasha-solomon** [comment]
Closing this issue since we're no longer removing the "Troubleshooting" section and because the "Technical preview" section was already removed for 8.15 and 8.16.
