### ISSUE TITLE
[Suggestion][Detection Engine] Cold/frozen filter

### ISSUE THREAD

**Issue by yctercero** [elastic/security-docs#5925]
### What can we change to make the docs better?

During team sync we discussed updating the language of the docs to try to clarify that addition of a tier filter would help ES better optimize not returning docs from those tiers, but it does not exclude the tiers in the way you might expect. That is, cold and frozen are still part of the search process. Some suggestions that were floated around during sync:

- Updating `Here is a sample Query DSL filter that excludes frozen tier data from a rule’s execution:` to something like `Here is a sample Query DSL filter that excludes documents from frozen tier being returned during a rule’s execution:`
- Updating `Rules that query cold and frozen data might perform more slowly. To exclude cold and frozen data, add a Query DSL filter that ignores cold and frozen [data tiers](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-tiers.html) when executing. You can add the filter when creating a new rule or updating an existing one.` to `Rules that query cold and frozen data might perform more slowly. To exclude cold and frozen documents from being returned, add a Query DSL filter that ignores cold and frozen [data tiers](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-tiers.html) when executing. You can add the filter when creating a new rule or updating an existing one.`
- Updating `Here is another sample Query DSL filter that excludes cold and frozen tier data from a rule’s execution:` to `Here is another sample Query DSL filter that excludes documents from cold and frozen tier from being returned during rule’s execution:`

### Doc URL

https://www.elastic.co/guide/en/security/master/exclude-cold-frozen-data-individual-rules.html

### Which documentation set needs improvement?

ESS only

### Software version

8.15+

**Comment by yctercero** [comment]
cc @marshallmain could you take a look at the suggestions and 👍🏽 or  👎🏽

**Comment by marshallmain** [comment]
I would suggest instead of 

> Rules that query cold and frozen data might perform more slowly. To exclude cold and frozen documents from being returned, add a Query DSL filter that ignores cold and frozen [data tiers](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-tiers.html) when executing. You can add the filter when creating a new rule or updating an existing one.

to say (changes in bold)

> Rules that query cold and frozen data might perform more slowly. To exclude cold and frozen documents from being returned, add a Query DSL filter that ignores cold and frozen [data tiers](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-tiers.html) when executing. **This can help Elasticsearch exclude cold and frozen data more efficiently.**  You can add the filter when creating a new rule or updating an existing one.

The wording 

> ... excludes documents from cold and frozen tier from being returned during ...

seems awkward to me. Maybe just
> ... excludes documents from cold and frozen tier during...

**Comment by marshallmain** [comment]
We'll definitely want to update the part `This setting does not apply to ES|QL or machine learning rules.` once we add support for that setting in the ES|QL rule implementation.

As far as language around `To ensure rules don’t search cold and frozen data when executing`, I think we should also center it on the results of the query instead of the "search" process - something like `To exclude results from cold and frozen data when executing`. The last phrase we have there `turning it on can improve rule performance and reduce execution time.` is good.

**Comment by nastasha-solomon** [comment]
> We'll definitely want to update the part This setting does not apply to ES|QL or machine learning rules. once we add support for that setting in the ES|QL rule implementation.

Yeah, absolutely. Though to clarify, in `8.16`, the `excludedDataTiersForRuleExecution` advanced setting doesn't apply to ES|QL rules, correct?

> As far as language around `To ensure rules don’t search cold and frozen data when executing`, I think we should also center it on the results of the query instead of the "search" process - something like `To exclude results from cold and frozen data when executing`. 

What are "results from cold and frozen data"? Are those events stored in cold and frozen data tiers or something else?

**Comment by marshallmain** [comment]
@vitaliidm is working on a PR to add support for `excludedDataTiersForRuleExecution` for 8.16 so I expect that we will support it, but not sure 100% until that is merged.

> What are "results from cold and frozen data"? Are those events stored in cold and frozen data tiers or something else?

Yeah results would just be events/documents in this case

**Comment by vitaliidm** [comment]
@marshallmain , @yctercero 

Should we add also that unavailable shards in frozen tier might cause rules failure?

**Comment by yctercero** [comment]
@vitaliidm 

> Should we add also that unavailable shards in frozen tier might cause rules failure?

I asked Sophie in https://github.com/elastic/sdh-elasticsearch/issues/8411 how we should talk about it. I think it is good to add language about it, but curious if we should describe it as known issue or just expected behavior.

**Comment by sophiec20** [comment]
According to our docs - _[Frozen tier](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-tiers.html#frozen-tier) nodes hold time series data that is accessed rarely and never updated._  ... and ... _searches on the frozen tier are typically slower than on the cold tier._

So, setting some wider context (but not attempting to write exact wording for docs) -- ideally:

- Data architectures are designed such that data required for mission critical alerting has availability guarantees -- by design, data with zero replicas, regardless of tier, is not highly available.
- The elasticsearch search APIs and the detection rules built upon them, should handle partial results (DSL, EQL, ES|QL) -- this is a known issue
- Users should not have to worry about excluding tiers when searching or configuring rules; by default we should not exclude certain tiers, but options are available if needed.

Suggest final wording be reviewed by @uric as there may be some amends to platform documentation also.
