### ISSUE TITLE
[DOCS] Add Dev Tools warning to Security App API subpages or code samples

### ISSUE THREAD

**Issue by peluja1012** [elastic/security-docs#646]
## Description 

When referring to our API docs, our users frequently falsely assume that our APIs can be used in the Kibana Dev Tools Console. This issue was previously [reported](https://github.com/elastic/security-docs/issues/412) and we [added](https://github.com/elastic/security-docs/pull/495) a warning to the main Security API docs page, as a result, explaining that the APIs can't be executed from Kibana Dev Tools. However, we need to go one step further and find more ways to communicate this to users.  Maybe we need to add a warning or information icon above the code samples. Or maybe we need to add the warning to API docs subpages as well. Open to suggestions!

https://www.elastic.co/guide/en/security/current/security-apis.html

![image](https://user-images.githubusercontent.com/616158/115928987-dcd67500-a43b-11eb-9d77-ae1473683c04.png)

**Comment by jmikell821** [comment]
Hi @peluja1012 thanks for raising this issue. We can start by adding a warning to the API subdoc pages, then we'll see if we need to add this warning elsewhere. We'll be sure to add this warning if we create new API code samples.

**Comment by nastasha-solomon** [comment]
I inserted the note into all API docs except for the following because they weren’t referenced [in this top-level topic](https://www.elastic.co/guide/en/security/master/security-apis.html).
- [Actions API (for pushing cases to external systems) ](https://www.elastic.co/guide/en/security/master/actions-api-overview.html)
- [Create connector](https://www.elastic.co/guide/en/security/master/register-connector.html)
- [Update connector](https://www.elastic.co/guide/en/security/master/update-connector.html)
- [Create or update an external incident](https://www.elastic.co/guide/en/security/master/cases-actions-api-execute.html)

@peluja1012, if the Kibana Dev Tools Console doesn't support these APIs either, I can insert the note into these topics as well.

**Comment by nastasha-solomon** [comment]
@peluja1012, I verified with @XavierM that the Kibana Dev Console does not support the Action APIs that push cases to external cases. Updating those last four topics now and will push the changes to the PR.
