### ISSUE TITLE
[DOCS] Osquery Manager: Review and revise integration overview

### ISSUE THREAD

**Issue by melissaburpo** [elastic/security-docs#649]
## Description 

In 7.13, the Asset Management team is releasing a v1 beta of a new Fleet integration: Osquery Manager. After some discussion in the #security-docs channel in slack with @jmikell821 and DeDe Morton, the plan we agreed on was for 7.13 to only document usage of the Osquery Manager integration in the README (this is the source for the overview displayed in the Fleet UI for the integration). We may add more info about the integration in the public Elastic docs in 7.14, but that is TBD.

The team has written a first draft of the Overview in this PR - https://github.com/elastic/integrations/pull/948 - which may be merged by the time this issue is picked up. If that PR is already closed, you can find the updated content here: https://github.com/elastic/integrations/tree/master/packages/osquery_manager/docs

We would very much like a docs expert to review and either directly revise or recommend updates on the Overview content. 

Please ping me or @james-elastic if you need more info about this request or if we can help in any way.

**Comment by nastasha-solomon** [comment]
@melissaburpo thanks for sharing these details! Just have a few follow-up questions before I start sending you my review notes:
- What's your preferred way of receiving editorial feedback? I'm currently editing the [the readme file](https://github.com/elastic/integrations/tree/master/packages/osquery_manager/docs) in a Word doc because it's easier for me to keep track of my thoughts with comments and track changes, but am happy to share my feedback a different way if you'd prefer something different. 
- Will the final readme file format support formatted text (i.e., bolded text, bulleted lists, etc.)? 
- Do you mind if I try to apply these instructions in a test Kibana environment? If yes, where can I find that env and what credentials should I use? I noticed a lot of references to UI elements (pages, columns, etc.) and language that orients the user in UI, so I was hoping to get a better sense of the workflow the user would be following as they use this feature. 
- What kind of sentence punctuation, if any, should the description text in the Exported Fields table have? Some descriptions end in periods, but many don't. 
- Do you mind if I send my feedback in batches or would you prefer that I send everything once? I'm nearly done with my initial run-through of the text before the Exported Fields table and, assuming nothing major comes up, should be able to get it to you by tomorrow. Reviewing the table will take another day, at least.

TIA for your help!

**Comment by melissaburpo** [comment]
Hi @nastasha-solomon, thanks for taking a look at the doc! Responses to your questions below:-

> What's your preferred way of receiving editorial feedback?

Google Docs work great, so that we can comment and collaborate on updates/revisions if needed.

> Will the final readme file format support formatted text (i.e., bolded text, bulleted lists, etc.)?

Yes, it supports basic Markdown for formatted text.

> Do you mind if I try to apply these instructions in a test Kibana environment?

That would be great! The integration is available in the latest BC for 7.13. You'll need a superuser account, and you'll need at least one agent set up in Fleet, so that you can add the integration and run queries. I'm still new around here, so I'm not 100% sure how to get you set up for something like that. Are there environments set up for the docs team to test stuff like that? Let me know if not, and I can work with our dev team to see if we can get you access to a system.

> What kind of sentence punctuation, if any, should the description text in the Exported Fields table have?

Great question. We actually pull those descriptions from an external resource, so I don't think we have a way to edit the field descriptions at the moment. We are able to edit all of the other content proceeding that though.

> Do you mind if I send my feedback in batches or would you prefer that I send everything once?

Whatever works best for you! But I do think you can skip reviewing the the exported fields descriptions, given the note above. Sorry, I should have mentioned that in the original request!

Thanks for taking a look at all this @nastasha-solomon!

**Comment by nastasha-solomon** [comment]
Thanks for getting back to me on this @melissaburpo! I'll drop my notes in a Google doc and share the link with you here once they're ready. I'll also abstain from reviewing the table since the descriptions are being pulled in from an external source and aren't editable. 

Regarding the test environment, I do have one that's managed by dev and it does look to have the Fleet feature installed. However, it appears that the Fleet Server host hasn't been set up yet and agents haven't been installed so I'd need to ping the team who manages the test env to help me do that. That said, if your dev team already has all these parts set up, I'd be happy to work with yours so I can get finish my review sooner than later. :)

**Comment by nastasha-solomon** [comment]
@melissaburpo edited docs are available [here](https://docs.google.com/document/d/1vfqBKkUwt-68E2-WgbH1ROLqAdBfBrkQMAoGQRrUzJc/edit?usp=sharing). Let me know if you're unable to access the Google doc and I'll share it with you directly. Otherwise, feel free to reach out if there are any edits I can clarify or you'd like additional reviews.
