### ISSUE TITLE
[BUG] Detection Rule execution authorization model not outlined in security docs

### ISSUE THREAD

**Issue by spong** [elastic/security-docs#822]
**Description**: Recently received a [discuss post](https://discuss.elastic.co/t/elastic-siem-detection-rule-query-permissions/279242) where a user was inquiring about the authorization model under which Detection Rules run. In searching through the security docs I wasn't able to find any reference outlining the details around this functionality, however I was able to find the below excerpt from the [Alerting docs](https://www.elastic.co/guide/en/kibana/current/alerting-getting-started.html#alerting-authorization):

>#### Authorization
>Rules, including all background detection and the actions they generate are authorized using an API key associated with the last user to edit the rule. Upon creating or modifying a rule, an API key is generated for that user, capturing a snapshot of their privileges at that moment in time. The API key is then used to run all background tasks associated with the rule including detection checks and executing actions.
>>If a rule requires certain privileges to run, such as index privileges, keep in mind that if a user without those privileges updates the rule, the rule will no longer function.

Not sure where this would best fit, but probably either on the Create Rules [page](https://www.elastic.co/guide/en/security/current/rules-ui-create.html), or perhaps our newly refined privileges matrix [page](https://www.elastic.co/guide/en/security/current/detections-permissions-section.html)?

**Comment by nastasha-solomon** [comment]
Verified with @spong that upcoming changes from RAC and RBAC will not affect the authorization model for rule execution. Because the model will remain the same, [the Kibana docs describing how the model works](https://www.elastic.co/guide/en/kibana/master/alerting-setup.html#alerting-authorization) will likely remain the same and we should be good to copy and paste them into both Security topics. I'm leaning towards copying and pasting the Kibana docs (instead of linking to them) because inserting the content directly into our Security topics keeps readers inside the Security docs and saves them a click. 

cc: @jmikell821

**Comment by nastasha-solomon** [comment]
Merged #889.
